uci-defaults: wifi_setup: Update wifi settings

diff --git a/target/linux/layerscape/base-files/etc/uci-defaults/92_wifi_setup b/target/linux/layerscape/base-files/etc/uci-defaults/92_wifi_setup
--- a/target/linux/layerscape/base-files/etc/uci-defaults/92_wifi_setup
+++ b/target/linux/layerscape/base-files/etc/uci-defaults/92_wifi_setup
@@ -1,6 +1,7 @@
 echo "wifi_setup : WiFi setup started." > /dev/kmsg
 
 board=$(cat /proc/cmdline | awk -F'board=' '{print $2}' | awk '{print $1}')
+mac_suffix=$(cat /proc/cmdline | awk -F'mac_suffix=' '{print $2}' | awk '{print $1}')
 
 [ -z "$board" ] && {
     echo "wifi_setup : board variable not found, WiFi setup failed." > /dev/kmsg
@@ -8,7 +9,13 @@ board=$(cat /proc/cmdline | awk -F'board=' '{print $2}' | awk '{print $1}')
     exit 1
 }
 
-uci set wireless.default_radio0.ssid="Connect-${board}-2.4GHz"
+[ -z "$mac_suffix" ] && {
+    echo "wifi_setup : mac_suffix variable not found, WiFi setup failed." > /dev/kmsg
+
+    exit 1
+}
+
+uci set wireless.default_radio0.ssid="Connect-${board}-${mac_suffix}-2.4GHz"
 uci set wireless.radio0.htmode='HE40'
 uci set wireless.radio0.channel='auto'
 uci set wireless.radio0.cell_density='3'
@@ -17,7 +24,7 @@ uci set wireless.radio0.disabled='0'
 uci set wireless.radio0.band='2g'
 uci set wireless.default_radio0.isolate='1'
 
-uci set wireless.default_radio1.ssid="Connect-${board}-5GHz"
+uci set wireless.default_radio1.ssid="Connect-${board}-${mac_suffix}-5GHz"
 uci set wireless.radio1.htmode='HE160'
 uci set wireless.radio1.channel='auto'
 uci set wireless.radio1.cell_density='3'
