wifi: ssid id

diff --git a/target/linux/qualcommbe/ipq95xx/base-files/etc/uci-defaults/93-wireless-setup b/target/linux/qualcommbe/ipq95xx/base-files/etc/uci-defaults/93-wireless-setup
--- a/target/linux/qualcommbe/ipq95xx/base-files/etc/uci-defaults/93-wireless-setup
+++ b/target/linux/qualcommbe/ipq95xx/base-files/etc/uci-defaults/93-wireless-setup
@@ -7,6 +7,17 @@ if grep -qx "$SCRIPT_NAME" "$STATE_FILE" 2>/dev/null; then
 	exit 0
 fi
 
+if [ -f /sys/class/net/wan/address ]; then
+    mac_suffix=$(awk -F: '{print $4$5$6}' /sys/class/net/wan/address 2>/dev/null)
+else
+    mac_suffix=''
+fi
+
+[ -z "$mac_suffix" ] && {
+    echo "wireless_setup : mac_suffix variable not found, Wi-Fi setup failed." > /dev/kmsg
+    exit 1
+}
+
 echo "wireless_setup : Wi-Fi setup started." > /dev/kmsg
 
 # OpenWrt-v25.12.5 related change:
@@ -47,7 +58,7 @@ uci set wireless.radio0.disabled='0'
 uci set wireless.default_radio0=wifi-iface
 uci set wireless.default_radio0.device='radio0'
 uci set wireless.default_radio0.mode='ap'
-uci set wireless.default_radio0.ssid="OpenWrt-Kiwi-2.4GHz"
+uci set wireless.default_radio0.ssid="Kiwi_DVK-${mac_suffix}-2.4GHz"
 uci set wireless.default_radio0.encryption='none'
 uci set wireless.default_radio0.isolate='0'
 uci set wireless.default_radio0.disassoc_low_ack='1'
@@ -71,7 +82,7 @@ uci set wireless.radio1.disabled='0'
 uci set wireless.default_radio1=wifi-iface
 uci set wireless.default_radio1.device='radio1'
 uci set wireless.default_radio1.mode='ap'
-uci set wireless.default_radio1.ssid="OpenWrt-Kiwi-5GHz"
+uci set wireless.default_radio1.ssid="Kiwi_DVK-${mac_suffix}-5GHz"
 uci set wireless.default_radio1.encryption='none'
 uci set wireless.default_radio1.isolate='0'
 uci set wireless.default_radio1.disassoc_low_ack='1'
